[project]
name = "supplychain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mealpy>=3.0.2",
    "numpy>=2.3.4",
    "plotly>=6.3.1",
]
